/*
 * This source file was generated by the Gradle 'init' task
 */
package paa.tp;

import paa.tp.controlador.ControladorJanela;

/**
 * Classe principal.
 */
public class App {
    /**
     * Função principal.
     * @param args Argumentos de linha de comando.
     */
    public static void main(String[] args) {
        final ControladorJanela controladorJanela = new ControladorJanela();
    }
}
